### ISSUE TITLE
Just upgraded to newest version 1.0.87 Keep getting error message.

### ISSUE THREAD

**Issue by sensei6375** [cbanack/comic-vine-scraper#411] opened 2015-06-14 10:13 UTC
Cant attach the log errors so here is a copy/paste of the smallest batch I tried.

--------------------------------------------------------------------------------
CV Scraper Version:  1.0.87
Running As:          ComicRack Plugin (CR version 0.9.176)
Cache Directory:     C:\Users\Stephen\AppData\Roaming\Comic Vine Scraper\localCache
Settings File:       C:\Users\Stephen\AppData\Roaming\Comic Vine Scraper\settings.dat
--------------------------------------------------------------------------------

--------------------------------------------------------------------
[X] Series          [X] Volume          [X] Number          
[X] Title           [X] Published       [X] Released        
[X] Crossovers      [X] Publisher       [X] Imprint         
[X] Writer          [X] Penciller       [X] Inker           
[X] Colorist        [X] Letterer        [X] Cover Art       
[X] Editor          [X] Summary         [X] Characters      
[X] Teams           [X] Locations       [X] Webpage         
-------------------------------------------------------------------
[X] Overwrite Existing        [ ] Ignore Blanks             
[X] Convert Imprints          [X] Autochoose Series         
[X] Download Thumbs           [X] Preserve Thumbs           
[ ] Confirm Issues            [X] Rescraping: Notes         
[X] Fast Rescrape             [X] Rescraping: Tags          
[X] Summary Dialog            
-------------------------------------------------------------------
Using scrape delay of 5 seconds.
Ignore all series published by 'abril'
Ignore all series published by 'editorial televisa'
Ignore all series published by 'panini'
Ignore all series published by 'planeta deagostini'
Ignore all series published by 'panini comics'
Ignore all series published by 'dino'
Ignore search term 'only'
Ignore search term 'fc'
Ignore search term 'nn'
Ignore search term 'tpbscan'
Ignore search term 'inc'
Ignore search term 'hc'
Ignore search term 'fixed'
Ignore search term 'covers'
Ignore search term 'digital'
Ignore search term 'empire'
Ignore search term 'gn'
Ignore search term 'tpb'
Ignore search term 'zone'
Ignore search term 'scanned'
Ignore search term 'charlton'
-------------------------------------------------------------------

======> scraping next comic book: 'The ZooHunters Vol 01 000 - Overtures (2014) (Digital''300) (Thornn-Empire).cbz'
trying to match this book automatically...
...couldn't find a match. leave it until the end.

======> scraping next comic book: 'The ZooHunters Vol 01 001 - Adagio for Her Kels (2014) (Digital''300) (Thornn-Empire).cbz'
trying to match this book automatically...
...couldn't find a match. leave it until the end.

======> scraping next comic book: 'The Zoohunters Vol 01 002 - Fegdam Fugue (2014) (Digital''300) (Thornn-Empire).cbz'
trying to match this book automatically...
...couldn't find a match. leave it until the end.

======> scraping next comic book: 'The ZooHunters Vol 01 000 (2014) (Digital-HD) (Thornn-Empire).cbz'
trying to match this book automatically...
------------------- PYTHON ERROR ------------------------
Caught ValueError: bad parameters
Traceback (most recent call last):
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 143, in scrape
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 257, in _ScrapeEngine__scrape
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 426, in _ScrapeEngine__scrape_book
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\automatcher.py", line 44, in find_series_ref
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\db.py", line 194, in query_issue_ref
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvdb.py", line 370, in query_issue_ref
  File "C:\Users\Stephen\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvconnection.py", line 118, in _query_issue_id_dom

wrote debug logfile: cvs-debug-log-2015-06-14 3.txt

**Comment by cbanack** [comment] 2015-06-14 18:16
Oops.   This is caused by a poorly done fix for issue 403.   Should be fixed now.

**Closed by cbanack** 2015-06-14 18:16 UTC
Labels: bug, priority
