### ISSUE TITLE
No longer pulls additional covers

### ISSUE THREAD

**Issue by Pachilles** [cbanack/comic-vine-scraper#444] opened 2016-09-01 17:38 UTC
When I click 'more covers', it always returns with 'Single Cover', even when more are available at comicvine.com.
Has comicvine changed it's format enough to break this?

Example page, Scraper stated as Single Cover:  http://comicvine.gamespot.com/broken-trinity-angelus-1/4000-149503/

**Comment by cbanack** [comment] 2016-09-01 18:37
Yes, unfortunately ComicVine does not offer variant covers in their public API.   The scraper used to pull that information directly off the ComicVine website, but ComicVine really didn't approve it this and banned the scraper until I took that functionality out.

So you are correct that the 'more covers' feature will never find more covers right now.   The obvious thing to do would be to remove the feature entirely, since it doesn't work...but the following thread at the ComicVine forum leads me to believe that variant/alternate cover images might eventually get added to the API.  If that happens, I can easily fix the 'more covers' feature.

**Comment by cbanack** [comment] 2016-09-01 18:39
Dupl

**Comment by cbanack** [comment] 2016-09-01 18:42
Closing as duplicate of issue #431.

**Closed by cbanack** 2016-09-01 18:42 UTC
