### ISSUE TITLE
Cannot Access Online Database

### ISSUE THREAD

**Issue by MrInveigler** [cbanack/comic-vine-scraper#430] opened 2016-02-18 04:22 UTC
So I've confirmed that there's nothing wrong with my internet, plus I've double checked my API Key. But I'm not sure why I'm getting this error. ComicRack has permission to go through the firewall, so I have no idea about the cause for this error.
I've also reinstalled Comic Scraper, ensuring I'm using the latest version. No luck.

Any help would be greatly appreciated.

**Comment by cbanack** [comment] 2016-02-18 05:29
This is a duplicate of issue 429.

The bug has been fixed in Comic Vine Scraper 1.0.92. which was released a few hours ago.

**Closed by cbanack** 2016-02-18 05:29 UTC
Labels: duplicate
