### ISSUE TITLE
API changed? Can't use the scraper?

### ISSUE THREAD

**Issue by CuddleBear92** [cbanack/comic-vine-scraper#472] opened 2020-02-29 19:29 UTC
Scraping fails, site is still up. something changed on the API side?

![ComicRack_suHsjCEsBf](https://user-images.githubusercontent.com/8496821/75613826-2f671a80-5b32-11ea-8471-890cdb63f4f1.png)

**Comment by cbanack** [comment] 2020-02-29 19:37
Duplicate of issue 471, should be fixed in CVS 1.0.100.

**Closed by cbanack** 2020-02-29 19:37 UTC

**Comment by CuddleBear92** [comment] 2020-02-29 20:16
oh, sorry about that. didn't check closed issues! <3
